### ISSUE TITLE
Does this have shortcuts for each VD (Virtual Desktop)?

### ISSUE THREAD

**Issue by migmolrod** [snaphat/virtual_desktop_enhancer#1]
With that I mean: is there a way to configure for example Alt+1 to activate VD1, Alt+2 to activate VD2, etc?

**Comment by snaphat** [comment]
Nah, but I can add that.

ETA: later today

**Comment by snaphat** [comment]
Added in 926a447c8d46083fe2d84bc62a708ec3c4249eeb.

Compiled release here:
https://github.com/snaphat/virtual_desktop_enhancer/releases/tag/v0.0.6

**Comment by snaphat** [comment]
Just occurred to me that maybe you also wanted shortcuts to move things to specific desktops?

The question I'd have is what shortcuts should those be? It's easy to add as well.

**Comment by snaphat** [comment]
I'm thinking of just doing this since this corresponds to the current left/right shortcuts:
Shortcut| Description
-- | --
Ctrl-Win-N | Switch to the virtual desktop N.
Win-Alt-N | Move window to the virtual desktop N.
Ctrl-Win-Alt-N | Move window & Switch to the virtual desktop N.

**Comment by migmolrod** [comment]
Nice! I'll try it later, I'm not in my main computer now. And yes, the additions to move them is great.

**Comment by snaphat** [comment]
See for the release with all of the shortcuts:
https://github.com/snaphat/virtual_desktop_enhancer/releases/tag/v0.0.7

**Comment by snaphat** [comment]
Erf, another update ...

There was a memory leak in the prior release(s) causing the memory usage to skyrocket overtime. It should only use about ~3-4MB memory usage now.

https://github.com/snaphat/virtual_desktop_enhancer/releases/tag/v0.0.8

**Comment by migmolrod** [comment]
It's nice, works like a charm. WIll close this, it's definitely solved

**Comment by snaphat** [comment]
FYI: there's a newer release that fixes a couple of bugs you may have encountered
