### ISSUE TITLE
Error: DesktopGUIDFromPtr 

### ISSUE THREAD

**Issue by a-chakrawarti** [snaphat/virtual_desktop_enhancer#3]
## Description

On closing a VD, error dialog pops up along with closed VD blue splash and sticks on the desktop till error dialog is closed.
</br>
![SharedScreenshot](https://user-images.githubusercontent.com/36135522/115118093-42031400-9fbf-11eb-85ef-14ca824305d7.jpg)

</br>

- Splash comes on top of the dialog box, so no way to press `OK`. 
- To close the error dialog box, press <kbd>Win + Tab</kbd> and close it from there.

## How to reproduce:

- Run `virtual_desktop_enchancer.exe`
- Add 4 more VDs (Virtual Desktops), in-total 5
- Switch to the 4th one
- Press <kbd>Win+Tab</kbd>
- Close the 5th VDs 
- Close the 4th VDs and error pops up

## Screenshot
![Screenshot 2021-04-17 162644](https://user-images.githubusercontent.com/36135522/115117495-7b865000-9fbc-11eb-9183-69f588252338.png)

**Comment by snaphat** [comment]
Noted, will fix today. I found another bug that causes explorer to crash when using the shortcuts while the taskview is active.

**Comment by snaphat** [comment]
Fixed by https://github.com/snaphat/virtual_desktop_enhancer/commit/f8fbe1c3ab6e2e5e0d9ee69f225edd3118525357. I will implement #2 before pushing a release.

**Comment by snaphat** [comment]
This is also working for you right, @a-chakrawarti ?

**Comment by a-chakrawarti** [comment]
Yea just tested it, couldn't reproduce. 🤩

**Comment by a-chakrawarti** [comment]
Closing the issue :D
